{
 "title": "Commerce Payment Circuit Breaker",
 "refresh": "5s",
 "panels": [
  {
   "title": "OPEN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(resilience4j_circuitbreaker_state{name=\"beeceptor-payment\"} == bool 1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HALF_OPEN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "(resilience4j_circuitbreaker_state{name=\"beeceptor-payment\"} == bool 2) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CLOSED",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "(resilience4j_circuitbreaker_state{name=\"beeceptor-payment\"} == bool 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "상세 지표 (실패율 및 호출량)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{name=\"beeceptor-payment\"}",
     "legendFormat": "실패율 (%)"
    },
    {
     "expr": "irate(resilience4j_circuitbreaker_calls_seconds_count{name=\"beeceptor-payment\"}[1m])",
     "legendFormat": "총 호출량 (TPS)"
    }
   ]
  }
 ]
}