global:
  scrape_interval: 20s
  evaluation_interval: 20s

scrape_configs:
  - job_name: 'core-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
