version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.34
    restart: always
    ports:
      - '13306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./core/mysql/initdb.d:/docker-entrypoint-initdb.d

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "19090:9090"
    volumes:
      - ./support/monitoring/infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "13000:3000"
    volumes:
      - ./support/monitoring/infra/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./support/monitoring/infra/grafana/datasources:/etc/grafana/provisioning/datasources

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "18086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin1234
